apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/jameskicklighter/hello-world-app:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: /mnt/storage   # 👈 matches UPLOAD_DIR in app.py
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: hello-world-pvc
