apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hello-world-app.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
