apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app.kubernetes.io/name: hello-world-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-world-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
